sudo: false
language: node_js
node_js:
  - 8
install:
  - npm install
script:
  - npm test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9e02cdc35fd353e37902
    on_success: change
    on_failure: always
    on_start: never
